project:
  name: terraform-aws-landing-zone
  code: eef16dcf
  include:
    - .
  exclude:
    - .git
    - node_modules
    - '**/.backup'
    - '**/.terraform'
terraform:
  varFile:
    - default.tfvars
  version: 0.12.16
template:
  provider:
    - aws:
        region: var.region
        allowed_account_ids:
          - var.account_id
    - aws:
        alias: default
        region: var.region
        allowed_account_ids:
          - var.account_id
    - aws:
        alias: sample
        region: var.sample_region
        assume_role:
          - role_arn: >-
              arn:aws:iam::var.sample_account_id:role/OrganizationAccountAccessRole
            session_name: var.sample_account_id
  tfvars:
    account_id: 123456789012
    region: us-east-1
    sample_account_id: 987654321098
    sample_region: us-east-1
