account_id = "123456789012"
region = "us-east-1"
landing_zone_components = {
  landing_zone_pipeline_s3_bucket = "s3://terraform-aws-landing-zone/mycompany/landing_zone_pipeline_s3_bucket/default.tfvars"
  landing_zone_pipeline_artifact_s3_bucket = "s3://terraform-aws-landing-zone/mycompany/landing_zone_pipeline_artifact_s3_bucket/default.tfvars"
  landing_zone_code_build_role = "s3://terraform-aws-landing-zone/mycompany/landing_zone_code_build_role/default.tfvars"
  landing_zone_code_build_role_policy = "s3://terraform-aws-landing-zone/mycompany/landing_zone_code_build_role_policy/default.tfvars"
  landing_zone_code_build = "s3://terraform-aws-landing-zone/mycompany/landing_zone_code_build/default.tfvars"
  landing_zone_code_pipeline_role = "s3://terraform-aws-landing-zone/mycompany/landing_zone_code_pipeline_role/default.tfvars"
  landing_zone_code_pipeline_role_policy = "s3://terraform-aws-landing-zone/mycompany/landing_zone_code_pipeline_role_policy/default.tfvars"
  landing_zone_code_pipeline = "s3://terraform-aws-landing-zone/mycompany/landing_zone_code_pipeline/default.tfvars"
  landing_zone_organization = "s3://terraform-aws-landing-zone/mycompany/landing_zone_organization/default.tfvars"
  landing_zone_organization_accounts = "s3://terraform-aws-landing-zone/mycompany/landing_zone_organization_accounts/default.tfvars"
  landing_zone_organization_unit = "s3://terraform-aws-landing-zone/mycompany/landing_zone_organization_unit/default.tfvars"
  landing_zone_organization_policy = "s3://terraform-aws-landing-zone/mycompany/landing_zone_organization_policy/default.tfvars"
  landing_zone_organization_policy_attachment = "s3://terraform-aws-landing-zone/mycompany/landing_zone_organization_policy_attachment/default.tfvars"
}
