component:
  name: landing_zone_route_vgw
  dependsOn:
    - landing_zone_route_table
    - landing_zone_gateway_vgw
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_route_table_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_data"]
      elements_landing_zone_gateway_vgw_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_vgw_data"]
      elements_landing_zone_route_vgw_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_vgw_resource"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_route_table:
        route_table_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_data"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          filter:
            name: 'tag:LzHash'
            values:
              - >-
                local.elements_landing_zone_route_table_data_map["config_${count.index}"]["LzHash"]
      aws_vpn_gateway:
        aws_vpn_gateway:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_vgw_data"])
          attached_vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          filter:
            - name: 'tag:LzHash'
              values:
                - >-
                  local.elements_landing_zone_gateway_vgw_data_map["config_${count.index}"]["LzHash"]
    resource:
      aws_route:
        landing_zone_route_vgw:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_vgw_resource"])
          route_table_id: 'element(data.aws_route_table.route_table_selected.*.id, count.index)'
          destination_cidr_block: >-
            local.elements_landing_zone_route_vgw_map["config_${count.index}"]["destination_cidr_block"]
          vpc_peering_connection_id: >-
            element(distinct(data.aws_vpn_gateway.aws_vpn_gateway.*.id),
            count.index)
    output:
      ids:
        value: aws_route.landing_zone_route_vgw.*.id
      thub_ids:
        value: aws_route.landing_zone_route_vgw.*.id
      landing_zone_route_vgw_ids:
        value: >-
          { for route_vgw in aws_route.landing_zone_route_vgw.*: route_vgw.id =>
          route_vgw.id }
