component:
  name: landing_zone_gateway_igw
  dependsOn:
    - landing_zone_vpc
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_gateway_igw_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_igw_tags"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
    resource:
      aws_internet_gateway:
        landing_zone_gateway_igw:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_igw_tags"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          tags: >-
            local.elements_landing_zone_gateway_igw_tags_map["config_${count.index}"]
    output:
      ids:
        value: aws_internet_gateway.landing_zone_gateway_igw.*.id
      thub_ids:
        value: aws_internet_gateway.landing_zone_gateway_igw.*.id
      landing_zone_gateway_igw_ids:
        value: >-
          { for gateway_igw in aws_internet_gateway.landing_zone_gateway_igw.*:
          gateway_igw.tags["Name"] => gateway_igw.id }
