component:
  name: landing_zone_security_group_rule_ingress
  dependsOn:
    - ../landing_zone_security_group
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_security_group_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_data"]
      elements_landing_zone_security_group_rule_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_rule_resource"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_security_group:
        security_group_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_data"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          name: >-
            local.elements_landing_zone_security_group_data_map["config_${count.index}"]["name"]
    resource:
      aws_security_group_rule:
        landing_zone_security_group_rule_ingress:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_rule_resource"])
          type: ingress
          protocol: >-
            local.elements_landing_zone_security_group_rule_map["config_${count.index}"]["protocol"]
          from_port: >-
            local.elements_landing_zone_security_group_rule_map["config_${count.index}"]["from_port"]
          to_port: >-
            local.elements_landing_zone_security_group_rule_map["config_${count.index}"]["to_port"]
          security_group_id: >-
            element(data.aws_security_group.security_group_selected.*.id,
            count.index)
          self: >-
            local.elements_landing_zone_security_group_rule_map["config_${count.index}"]["self"]
          description: >-
            local.elements_landing_zone_security_group_rule_map["config_${count.index}"]["description"]
          cidr_blocks: >-
            compact(split("|",
            local.elements_landing_zone_security_group_rule_map["config_${count.index}"]["cidr_blocks"]))
          ipv6_cidr_blocks: >-
            compact(split("|",
            local.elements_landing_zone_security_group_rule_map["config_${count.index}"]["ipv6_cidr_blocks"]))
          prefix_list_ids: >-
            compact(split("|",
            local.elements_landing_zone_security_group_rule_map["config_${count.index}"]["prefix_list_ids"]))
    output:
      ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_security_group_rule.landing_zone_security_group_rule_ingress.*.id)
      thub_ids:
        value: >-
          map("${tfvar.terrahub["landing_zone_providers"]["0"]}",
          aws_security_group_rule.landing_zone_security_group_rule_ingress.*.id)
