component:
  name: landing_zone_vpc_endpoint_interface
  dependsOn:
    - landing_zone_vpc
    - landing_zone_subnet
    - landing_zone_security_group
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_subnets_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_subnets_data"]
      elements_landing_zone_security_groups_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_groups_data"]
      elements_landing_zone_vpc_endpoint_interface_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_endpoint_interface_tags"]
      elements_landing_zone_vpc_endpoint_interface_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_endpoint_interface_resource"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_subnet_ids:
        subnet_ids_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_subnets_data"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          filter:
            name: cidr-block
            values: >-
              split("|",
              local.elements_landing_zone_subnets_data_map["config_${count.index}"]["cidr_blocks"])
      aws_security_groups:
        security_groups_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_groups_data"])
          filter:
            - name: vpc-id
              values:
                - 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
            - name: 'tag:zHash'
              values:
                - >-
                  local.elements_landing_zone_security_groups_data_map["config_${count.index}"]["zHash"]
    resource:
      aws_vpc_endpoint:
        landing_zone_vpc_endpoint_interface:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_endpoint_interface_resource"])
          service_name: >-
            local.elements_landing_zone_vpc_endpoint_interface_map["config_${count.index}"]["service_name"]
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          policy: >-
            local.elements_landing_zone_vpc_endpoint_interface_map["config_${count.index}"]["policy"]
          private_dns_enabled: >-
            local.elements_landing_zone_vpc_endpoint_interface_map["config_${count.index}"]["private_dns_enabled"]
          security_group_ids: >-
            element(data.aws_security_groups.security_groups_selected.*.ids,
            count.index)
          subnet_ids: 'element(data.aws_subnet_ids.subnet_ids_selected.*.ids, count.index)'
          tags: >-
            merge(local.elements_landing_zone_vpc_endpoint_interface_tags_map["config_${count.index}"],
            map("zHash", sha1("${tfvar.terrahub["project"]["code"]}
            ${tfvar.terrahub["component"]["name"]}
            ${tfvar.terrahub["landing_zone_providers"]["0"]}
            ${local.elements_landing_zone_vpc_endpoint_interface_map["config_${count.index}"]["service_name"]}")))
          vpc_endpoint_type: Interface
    output:
      ids:
        value: aws_vpc_endpoint.landing_zone_vpc_endpoint_interface.*.id
      thub_ids:
        value: aws_vpc_endpoint.landing_zone_vpc_endpoint_interface.*.id
      landing_zone_vpc_endpoint_interface_ids:
        value: >-
          { for vpc_endpoint_interface in
          aws_vpc_endpoint.landing_zone_vpc_endpoint_interface.*:
          lookup(vpc_endpoint_interface.tags, "zHash",
          vpc_endpoint_interface.id) => vpc_endpoint_interface.id }
