component:
  name: landing_zone_ssm_association_by_instance_id
  template:
    locals:
      elements_landing_zone_instance_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_instance_data"]
      elements_landing_zone_ssm_association_by_instance_id_arg_parameters_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_association_by_instance_id_resource_arg_parameters"]
      elements_landing_zone_ssm_association_by_instance_id_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_association_by_instance_id_resource"]
    data:
      aws_instance:
        instance_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_instance_data"])
          filter:
            name: 'tag:Name'
            values:
              - >-
                local.elements_landing_zone_instance_data_map["config_${count.index}"]["name"]
    resource:
      aws_ssm_association:
        landing_zone_ssm_association_by_instance_id:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_association_by_instance_id_resource"])
          name: >-
            local.elements_landing_zone_ssm_association_by_instance_id_map["config_${count.index}"]["name"]
          association_name: >-
            local.elements_landing_zone_ssm_association_by_instance_id_map["config_${count.index}"]["association_name"]
          document_version: >-
            local.elements_landing_zone_ssm_association_by_instance_id_map["config_${count.index}"]["document_version"]
          instance_id: 'element(data.aws_instance.instance_selected.*.id, count.index)'
          output_location:
            s3_bucket_name: >-
              local.elements_landing_zone_ssm_association_by_instance_id_map["config_${count.index}"]["ol_s3_bucket_name"]
            s3_key_prefix: >-
              local.elements_landing_zone_ssm_association_by_instance_id_map["config_${count.index}"]["ol_s3_key_prefix"]
          parameters: >-
            local.elements_landing_zone_ssm_association_by_instance_id_arg_parameters_map["config_${count.index}"]
          schedule_expression: >-
            local.elements_landing_zone_ssm_association_by_instance_id_map["config_${count.index}"]["schedule_expression"]
          compliance_severity: >-
            local.elements_landing_zone_ssm_association_by_instance_id_map["config_${count.index}"]["compliance_severity"]
          max_concurrency: >-
            local.elements_landing_zone_ssm_association_by_instance_id_map["config_${count.index}"]["max_concurrency"]
          max_errors: >-
            local.elements_landing_zone_ssm_association_by_instance_id_map["config_${count.index}"]["max_errors"]
    output:
      association_ids:
        value: >-
          aws_ssm_association.landing_zone_ssm_association_by_instance_id.*.association_id
      instance_ids:
        value: >-
          aws_ssm_association.landing_zone_ssm_association_by_instance_id.*.instance_id
      names:
        value: aws_ssm_association.landing_zone_ssm_association_by_instance_id.*.name
      parameters:
        value: >-
          aws_ssm_association.landing_zone_ssm_association_by_instance_id.*.parameters
      landing_zone_ssm_association_by_instance_id_ids:
        value: >-
          { for ssm_association_by_instance_id in
          aws_ssm_association.landing_zone_ssm_association_by_instance_id.*:
          ssm_association_by_instance_id.name =>
          ssm_association_by_instance_id.id }
      landing_zone_ssm_association_by_instance_id_names:
        value: >-
          { for ssm_association_by_instance_id in
          aws_ssm_association.landing_zone_ssm_association_by_instance_id.*:
          ssm_association_by_instance_id.name =>
          ssm_association_by_instance_id.name }
