component:
  name: landing_zone_tgw_route
  dependsOn:
    - landing_zone_vpc
    - landing_zone_tgw_vpc_attachment
    - landing_zone_gateway_tgw
    - landing_zone_tgw_route_table
  template:
    locals:
      elements_landing_zone_tgw_route_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_tgw_route_resource"]
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_tgw_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_tgw_data"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_ec2_transit_gateway_vpc_attachment:
        tgw_vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: length(data.aws_vpc.vpc_selected.*.id)
          filter:
            name: vpc-id
            values:
              - 'element(data.aws_vpc.vpc_selected.*.id , count.index)'
      aws_ec2_transit_gateway:
        gateway_tgw_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_tgw_data"])
          filter:
            - name: options.amazon-side-asn
              values:
                - >-
                  local.elements_landing_zone_tgw_data_map["config_${count.index}"]["amazon_side_asn"]
      aws_ec2_transit_gateway_route_table:
        route_table_tgw_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: length(data.aws_ec2_transit_gateway.gateway_tgw_selected.*.id)
          filter:
            - name: transit-gateway-id
              values:
                - >-
                  element(data.aws_ec2_transit_gateway.gateway_tgw_selected.*.id,
                  count.index)
    resource:
      aws_ec2_transit_gateway_route:
        landing_zone_tgw_route:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_tgw_resource"])
          destination_cidr_block: >-
            local.elements_landing_zone_tgw_route_map["config_${count.index}"]["destination_cidr_block"]
          transit_gateway_attachment_id: >-
            element(data.aws_ec2_transit_gateway_vpc_attachment.tgw_vpc_selected.*.id
            , count.index)
          transit_gateway_route_table_id: >-
            element(data.aws_ec2_transit_gateway_route_table.route_table_tgw_selected.*.id
            , count.index)
    output:
      ids:
        value: aws_ec2_transit_gateway_route.landing_zone_tgw_route.*.id
      thub_ids:
        value: aws_ec2_transit_gateway_route.landing_zone_tgw_route.*.id
      landing_zone_tgw_route_ids:
        value: >-
          { for tgw_route in
          aws_ec2_transit_gateway_route.landing_zone_tgw_route.*: tgw_route.id
          => tgw_route.id }
