component:
  name: landing_zone_route_ipv6
  dependsOn:
    - landing_zone_route_table
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_route_table_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_data"]
      elements_landing_zone_route_ipv6_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_ipv6_resource"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_route_table:
        route_table_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_data"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          filter:
            name: 'tag:LzHash'
            values:
              - >-
                local.elements_landing_zone_route_table_data_map["config_${count.index}"]["LzHash"]
    resource:
      aws_route:
        landing_zone_route_ipv6:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_ipv6_resource"])
          route_table_id: 'element(data.aws_route_table.route_table_selected.*.id, count.index)'
          destination_ipv6_cidr_block: >-
            local.elements_landing_zone_route_ipv6_map["config_${count.index}"]["destination_ipv6_cidr_block"]
    output:
      ids:
        value: aws_route.landing_zone_route_ipv6.*.id
      thub_ids:
        value: aws_route.landing_zone_route_ipv6.*.id
      landing_zone_route_ipv6_ids:
        value: >-
          { for route_ipv6 in aws_route.landing_zone_route_ipv6.*: route_ipv6.id
          => route_ipv6.id }
